services:
  postgres:
    image: postgres:17.4.alpine
    container_name: nestjs_potgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'

  app:
    build: .
    container_name: nestjs_app
    restart: always
    depends_on:
      - postgres
    ports:
      - '4000:3001'
    environment:
      DATABASE_URL: 'postgresql://user:password@postgres:5432/mydb'
    command: ['npm', 'run', 'start:migrate:prod']

volumes:
  pgdata: